package lambdaDB.query.executer;

public enum Commands {
    CREATE_TABLE,
    CREATE_TABLE_FIELD,
    CREATE_TABLE_FIELD_DEFAULT_STRING,
    CREATE_TABLE_FIELD_DEFAULT_INT,
    CREATE_TABLE_FIELD_DEFAULT_NULL,
    CREATE_TABLE_FIELD_PRIMARY_KEY,
    CREATE_TABLE_FIELD_AUTOINCREMENT,
    CREATE_TABLE_FIELD_TYPE_SIZE,
    CREATE_TABLE_COMMIT,
    CREATE_TABLE_FIELD_NOT_NULL
}
